export const RESPONSE_TYPE_JSON = 'json'
export const RESPONSE_TYPE_ARRAY_BUFFER = 'arraybuffer'
export const RESPONSE_TYPE_BLOB = 'blob'
export const RESPONSE_TYPE_DOCUMENT = 'document'
export const RESPONSE_TYPE_TEXT = 'text'
